name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    name: Build on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: poetry

      - name: Install dependencies
        run: |
          poetry install
          poetry self add "poetry-dynamic-versioning[plugin]"

      - name: Build program
        run: poetry run build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: pb-${{ matrix.os }}
          path: dist/precise_bet/
